name: 01 - building blocks
on: push
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "hello workd!"
    echo-goockby:
        runs-on: ubuntu-latest
        steps:
            - name: success step
              run: |
                echo "i will succedd"
                exit 0
            - name: say goodbye
              run: echo "Goodbye"