name: 02 - Workflow events
on:
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:

jobs: 
    eco:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "i have been triggerd a(n) ${{github.event_name}} event."
    