name: 03 - workflow runners
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show OS
              run: |
                echo "this job is runninng on ubuntu runner."
                echo "runner OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
          - name: show OS
            run: |
              echo "this job is runninng on ubuntu runner."
              echo "runner OS: $RUNNER_OS"
