name: 03 - workflow runners
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latests
        steps:
            - name: show OS
              run: |
                echo "this job is runninng on ubuntu runner."
                echo "runner OS: $RUNNER_OS"