name: 06 - context
on: 
    push:
    workflow_dispatch:
jobs:
  echo-data:
      runs-on: ubuntu-latest
      steps: 
      - name: Display info
        run: |
                echo "Event Name: ${{github.event_name}}"
                echo "ref:${{github.ref}}"
                echo "SHA ${{github.sha}}"
                echo "actor ${{github.actor}}"
                ecto "workflow ${{github.workflow}}"
                echo "run ID ${{github.run_id}}"
                echo "run number ${{github.run_number}}"
      - name: Retrieve variable
        run: |
                echo "variable value ${{vars.MY_VAR}}"
