name: 07 - using e3xpressions
run-name: 07 - using expressions| DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: "[debug] Print startup-up"
          if: ${{inputs.debug}}
          run: |
            echo "Triggered by ${{github.event_name}}"
            echo "Branch: ${{github.ref}}"
            echo "Commit sha; ${{github.sha}}"
            echo "runner OS: ${{runner.os}}"
        - name: "[debug] Print when triggered from main"
          if: ${{inputs.debug && github.ref== 'refs/heads/main'}}
          run: echo "I was triggered fvrom main"
        - name: Greeting
          run: echo "hello world"
