name: 08 -  using Variables
on:
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: "i am a workflow env var"  
    OVERWRITTEN: "I will be overwritte"      
    UNDEFINED_VAR_WITH_DEFAULT: ${{vars.UNDEFINED_VAR || 'default value'}}"
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I AM A JOB ENV VAR"
            OVERWRITTEN: "I have been overwritten at job level"
        steps:
            - name: Pring Env variables
              env:
                STEP_VAR: "i am sa ste env var"
                step_var2: "i am anoteher step env var"
              run: |
                echo "Step env var: ${{env.STEP_VAR}}"
                echo "sten env var2: $step_var2"
                echo "job env var:; ${{env.JOB_VAR}}"
                echo "workflow env var:; ${{env.WORKFLOW_VAR}}"
                echo "Overwritten: ${{env.OVERWRITTEN}}"
            - name: overwrite job variable
              env: 
                OVERWRITTEN: "I HAVE BEEN OVERWRITEN AT STEP LVL"
              run: |
                echo "sten env var: ${{env.OVERWRITTEN}}"
    echo2:
        runs-on: ubuntu-latest
        steps:
            - name: Print variables
              run: |
                echo "org var: ${{vars.ORG_VAR}}"
                echo "org overwritten var: ${{vars.OVERWRITTEN_VAR}}"
                echo "repo var: ${{vars.REPOSTIROY_VAR}}"
    echo-prod:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: print prod variables
              run: |
                echo "org var: ${{vars.ORG_VAR}}"
                echo "org overwritten var: ${{vars.OVERWRITTEN_VAR}}"
                echo "repo var: ${{vars.REPOSTIROY_VAR}}"
                echo "enviroment var ${{vars.TARGET_VAR}}"
    echo-undefined:
         runs-on: ubuntu-latest
         steps:
            - name: Print undefinded variablesvariables
              run: |
                echo "org var: ${{env.UNDEFINED_VAR_WITH_DEFAULT}}"
              
