name: 11 -  working with imputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                # other types are choice, enviroment and boolean
                description: skip deployjment and only print build output
                default: false
            target:
                type: environment
                required: true
                description: which enviroment the workflow will target
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: release from which to build and deploy
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "building from ${{inputs.tag}}"
    deploy:
        runs-on: ubuntu-latest
        if: ${{!inputs.dry-run}}
        environment: ${{inputs.target}}
        needs: build
        steps:
            - name: deploy
              run: echo "deploying to ${{inputs.target}}"