name: 13 - using caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: wheter to exectutee cache step
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x
jobs:
    install-deps:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        outputs:
          deps-cache-key: ${{steps.cache-key.CACHE_KEY}}
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}
            - name: calculate cache key
              id: cache-key
              run: |
                echo "CACHE_KEY=deps-node-modules-${{hashFiles('13-caching/react-app/package-lock.json')}}" >> "GITHUB_OUTPUT"
            - name: download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path: ${{steps.cache-key.outputs.CACHE_KEY}}

            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
    lint-test:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}
        #1. checkout the code
            - name: download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: ${{needs.install-deps.outputs.deps-cache-key}}
            - name: testing
              run: npm run test
            - name: linting
              run: echo  "Linting...."
            - name: deploy to nonprod
              run: echo "dedploy to non prod"
        #2. install dependencies
        #3. unit testing and building app
        #4. deploy to nonprod environment

    build:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}
            - name: download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: ${{needs.install-deps.outputs.deps-cache-key}}
            - name: building
              run: npm run build