name: 13 - using caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: wheter to exectutee cache step
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}
        #1. checkout the code
            - name: install dependencies
              run: npm ci
            - name: testing
              run: npm run test
            - name: building
              run: npm run build
            - name: deploy to nonprod
              run: echo "dedploy to non prod"
        #2. install dependencies
        #3. unit testing and building app
        #4. deploy to nonprod environment