name: 15 - working with matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        name: ${{matrix.os}}-${{matrix.node-version}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: true
            matrix:
                node-version: [18.x , 20.x , 21.x]
                os:
                    - ubuntu-latest
                    #- macos-latest removed due to expensive
                    - windows-latest    
                #to add a specific version
                include: 
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
            - name: setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{matrix.node-version}}
            - name: fail if experimental
              if: matrix.tag =='experimental'
              run: exit 1
            - name: perform some tests
              run: |
                echo "runnign test on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
                sleep 10
            - name: upload test restuls
              run: echo "uploading test results"
    include-example:
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
        runs-on: ubunty-latest
        strategy:
            matrix:
                color: [red, gree]
                shape: [circle, square]
                size: [small, large]
                include:
                    - color: red
                      shape: triangle
        steps:
            - name:
              run: echo "${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}"
